repos:
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 'v2.11.1'
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.14.6'
    hooks:
      - id: ruff-check
        name: ruff
        args: ['--fix']

  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.2
    hooks:
      - id: bandit
        args: ['-r', '-lll']

  - repo: https://github.com/pylint-dev/pylint
    rev: v4.0.3
    hooks:
      - id: pylint
        types: [python]
        additional_dependencies:
          - fastapi==0.121.3
          - loguru==0.7.3
          - pydantic==2.12.4
          - pydantic-settings==2.12
          - uvicorn==0.38.0
          - inject==5.3.0
          - web3==7.14.0
          - pytest==9.0.1

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies:
          - fastapi==0.121.3
          - loguru==0.7.3
          - pydantic==2.12.4
          - pydantic-settings==2.12
