# The workflow checks out the repository, installs pre-commit, and runs the autoupdate command.
# If there are any updates, it creates a pull request with the changes.

name: Pre-commit Update

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: read

jobs:
  auto-update:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: '0.9.11'
          python-version: '3.13'

      - name: Install dependencies
        run: |
          uv sync --all-groups --frozen

      - name: Autoupdate pre-commit hooks
        working-directory: '.'
        run: uv run pre-commit autoupdate

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          token: ${{ env.GH_TOKEN }}
          branch: chore/pre-commit-autoupdate
          title: Update pre-commit hooks
          commit-message: 'chore(config): update pre-commit hooks'
          body: |
            This PR was created automatically by the pre-commit autoupdate workflow.
            It updates the pre-commit hooks to their latest versions.
          labels: update
